# Generated by Django 4.2.4 on 2023-08-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_machine', models.CharField(max_length=255)),
                ('number_engine', models.CharField(max_length=255)),
                ('number_transmission', models.CharField(max_length=255)),
                ('number_driving_axle', models.CharField(max_length=255)),
                ('number_steering_axle', models.CharField(max_length=255)),
                ('supply_contract', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('end_consumer', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('options', models.TextField(max_length=1000)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.client')),
                ('model_driving_axle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.drivingaxle')),
                ('model_engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.engine')),
                ('model_equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RefusalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255)),
                ('description', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_time', models.IntegerField(default=0)),
                ('order_number', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.machine')),
                ('maintenance_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.maintenancecompany')),
                ('service_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.typemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='model_steering_axle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.steeringaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_transmission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.transmission'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refusal_date', models.DateField()),
                ('operating_time', models.IntegerField(default=0)),
                ('refusal_description', models.TextField(max_length=1000)),
                ('repair_parts', models.TextField(max_length=1000)),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.machine')),
                ('recovery_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.recoverymethod')),
                ('refusal_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.refusalnode')),
                ('service_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany')),
            ],
        ),
    ]
