# Generated by Django 4.2.4 on 2023-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_claim_recovery_method_alter_claim_refusal_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='number_machine',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
