# Generated by Django 4.2.4 on 2023-08-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silant', '0004_alter_claim_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_link',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
