# Generated by Django 4.2.4 on 2023-08-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silant', '0006_alter_client_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecompany',
            name='user_link',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
